name: clerk_auth
description: Package that will allow you to authenticate and use Clerk from Dart code.
version: 0.0.3-dev
homepage: https://clerk.com/docs
repository: https://github.com/clerk/clerk-sdk-flutter/tree/main/packages/clerk_auth
issue_tracker: https://github.com/clerk/clerk-sdk-flutter/labels/package%3A%20clerk_auth
topics:
  - authentication

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dart_jsonwebtoken: ^2.14.0
  http: ^1.2.0
  json_annotation: ^4.9.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.9
  dart_dotenv: ^1.0.1
  json_serializable: ^6.8.0
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
  uuid: ^4.4.2
