name: clerk_auth
description: Package that will allow you to authenticate and use Clerk from Dart code.
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  dart_jsonwebtoken: ^2.14.0
  http: ^1.2.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  common: any

dev_dependencies:
  build_runner: ^2.4.9
  dart_dotenv: ^1.0.1
  uuid: ^4.4.2
  clerk_analysis: any
  json_serializable: ^6.8.0
  test: ^1.24.0
