name: clerk_sdk
version: 0.0.12-beta
description: >
  Clerk SDK containing all packages that define use of Clerk 
  services for Dart and Flutter code.
environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.4'

dev_dependencies:
  melos: ^6.3.2
