name: clerk_analysis
description: Lints for all Clerk packages
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  lints: ^4.0.0
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.
