name: Feature request
description: Suggest a new idea for the Clerk SDK for Flutter and Dart.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the Clerk SDK for Flutter and Dart!

        If you are looking for support, please check out:
          - https://clerk.com/docs
          - https://flutter.dev/
          - https://api.flutter.dev/
  - type: markdown
    attributes:
      value: |
        Before filling the form fields, please consider the following:
        - Ensure that you have searched the [existing issues](https://github.com/devangels/clerk_sdk/issues)
  - type: textarea
    attributes:
      label: Use case
      description: |
        Please tell us the problem you are running into that led to you wanting
        a new feature.

        Is your feature request related to a problem? Please give a clear and
        concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Briefly but precisely describe what you would like the SDK to be able to do.

        Consider attaching something showing what you are imagining:
         * images
         * videos
         * code samples
    validations:
      required: true