blank_issues_enabled: true
contact_links:
  - name: I need help with the Clerk SDK for Flutter and Dart
    about: Having a problem with the `clerk_auth` or `clerk_flutter` packages? Raise an issue here