name: common
description: A package containing shared dart libraries.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  logging: ^1.2.0


dev_dependencies:
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
