name: clerk_flutter
description: Package that will allow you to authenticate and use Clerk from Flutter code.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  clerk_auth: any
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_svg: ^2.0.10+1
  common: any
  webview_flutter: ^4.8.0

dev_dependencies:
  clerk_analysis: any
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
