name: clerk_flutter
description: Package that will allow you to authenticate and use Clerk from Flutter code.
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  clerk_auth: any
  flutter:
    sdk: flutter

dev_dependencies:
  clerk_analysis:
    path: ../clerk_analysis
  flutter_test:
    sdk: flutter

flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
