name: clerk_flutter_example
description: Example application for linking to clerk_flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  clerk_flutter:
    path: ../
  clerk_auth:
    path: ../../clerk_auth/

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
