name: clerk_auth_example
description: "ClerkAuth example"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  clerk_flutter:
    path: ../
  flutter_dotenv: ^5.2.1
  common:
    path: ../../common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.example
