name: widgetbook_workspace
description: A storybook for clerk_flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0
  clerk_flutter: any
  faker: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.8.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
