name: clerk_api
description: Package for defining the communication with Clerk API services.
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dev_dependencies:
  clerk_analysis:
    path: ../clerk_analysis
  test: ^1.24.0
